<?php

namespace AppBundle\Repository;

/**
 * BelegRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BelegRepository extends \Doctrine\ORM\EntityRepository
{
}
