<?php

namespace AppBundle\Repository;

/**
 * BroodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BroodRepository extends \Doctrine\ORM\EntityRepository
{
}
