<?php

namespace AppBundle\Repository;

/**
 * SoepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoepRepository extends \Doctrine\ORM\EntityRepository
{
}
